### ISSUE TITLE
Question about output labels

### ISSUE THREAD

**Issue by JadinTredupLP** [jasonwu0731/ToD-BERT#23]
Hello, I am working on re-implementing the tod-bert code to run on my own pretraining dataset and I have been getting a CUDA error that seems to be stemming from incorrect inputs to the loss function. Upon further examination it seems I might not be understanding the output labels for the responses in the RCL task. I had thought the output labels would be 1 if it is the correct response, and zero if incorrect. However, the line of code that generates the output seems to just generate an incrementing array relative to the batch size.  
  
Specifically at the [following line](https://github.com/jasonwu0731/ToD-BERT/blob/5022baca429c97488b6cb475ce2f589cdc06b7db/my_tod_pretraining.py#L212)  
`output_labels = torch.tensor(np.arange(batch_size)).long() #.to(args.device)`  
  
For a batch size of 8 for example, the output labels would be an array [0, 1, 2, 3, 4, 5, 6, 7]. Is this to be expected? If so, how does this correspond to the positive/negative response labels needed?

Thanks in advanced!

**Comment by duongkstn** [comment]
read this piece of code thoroughly: (`my_tod_pretraining.py`)
```
# Calculate RCL loss
                scores = torch.matmul(hid_cont, hid_resp.transpose(1, 0))
                loss_rs = xeloss(scores, resp_label)
                loss += loss_rs
                loss_rs = loss_rs.item()
```
Suppose you have a batch of 8 samples, you calculate "confusion matrix" `scores` (size 8x8). With regards to 3rd sample, for example, you have a vector 8x1 and you have to classify with label 3 (it means that in 8 features of this sample, label 3 has to be the truly choice because "3" only matches with "3", not "0", "1", "2", "4",.."8"). In a nutshell, Label of N-th sample is N.

Sr for bad English but hope you understand !
